### ISSUE TITLE
Error in docker-compose pull

### ISSUE THREAD

**Issue by aron010** [seibert-media/erpnext-docker#9]
`manifest for quay.io/seibertmedia/erpnext:latest is not found.`
I edited my docker-compose.yml file to `quay.io/seibertmedia/erpnext:'master'` since there is no 'latest' version. 

Please correct this on this master version as well so it will be fine for future installs.

**Comment by bborbe** [comment]
Have you done `docker-compose build`?

**Comment by aron010** [comment]
Hello @bborbe thanks for your reply!

Yes i have done `docker-compose build` but as I mentioned, everything is fine on my side. 
But for future clones of this repo it needs to be changed. You can build the docker containers but first you need to pull them. The erpnext container is not pulled because the 'latest' tag does not exist in the docker repo. It should be 'master' as I mentioned above. So the docker-compose.yml file needs to be updated in the master branche.

**Comment by bborbe** [comment]
Works on my machine ;) I have tried it and after docker-compose build the image with tag latest exists. `docker-compose build` create the docker image locally. So u don't have to pull a image.

```
docker images |grep quay.io/seibertmedia/erpnext | wc -l 
0

docker-compose build

docker images |grep quay.io/seibertmedia/erpnext | wc -l 
1
```
